### ISSUE TITLE
Method 'f' not found for invocant of class 'Seq'

### ISSUE THREAD

**Issue by pjscott** [labster/perl6-File-Find-Duplicates#5]
Broken in recent Rakudo:

==> Building File::Find::Duplicates
==> Testing File::Find::Duplicates
Method 'f' not found for invocant of class 'Seq'
  in sub find_duplicates at /Users/peter/.panda-work/1450147197_1/lib/File/Find/Duplicates.pm6:17
  in sub find-sorted at t/00-basic.t:15
  in block <unit> at t/00-basic.t:22

This is rakudo version 2015.11-525-ga342eb1 built on MoarVM version 2015.11-44-ge7edb06 implementing Perl v6.b

**Comment by labster** [comment]
Fixed in 978e4f9c.  I hadn't updated this for the GLR due to too much $dayjob, but it's good now.
Thanks for the report!
